[workspace]
resolver = "2"
members = [
    "lc",
    "cli",
    "bitcoin",
    "sp1/cli",
    "risc0/cli",
    "sp1/program",
    "risc0/methods",
]

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
lto = "thin"
overflow-checks = true
