[package]
version = "0.1.0"
name = "bitcoinz-script"
edition = "2021"

[dependencies]
bitcoin = { path = "../bitcoin" }
tokio = { version = "1.36.0", features = [ "full"] }
clap = { version = "4.5.2", features = ["derive"]}
sp1-core = { git = "https://github.com/succinctlabs/sp1.git" }
