[workspace]
[package]
version = "0.1.0"
name = "bitcoinz-script"
edition = "2021"

[dependencies]
clap = "4.5.2"
derive-getters = "0.3.0"
sp1-core = { git = "https://github.com/succinctlabs/sp1.git" }
